apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-router-monitor
  namespace: monitoring
  labels:
    app: model-router
    component: monitoring
    smm.architect/service: model-router
spec:
  jobLabel: model-router
  selector:
    matchLabels:
      app: model-router
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'model_router_.*'
      action: keep
    - sourceLabels: [workspace_id]
      targetLabel: workspace
      replacement: '${1}'
    - sourceLabels: [agent_type]
      targetLabel: agent
      replacement: '${1}'
  - port: http
    path: /health/metrics
    interval: 60s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'up|model_router_health_.*'
      action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smm-canary-deployments
  namespace: monitoring
  labels:
    app: model-router
    component: canary-monitoring
    smm.architect/service: canary-deployments
spec:
  jobLabel: canary-deployments
  selector:
    matchLabels:
      app: model-router
      component: canary
  endpoints:
  - port: http-metrics
    path: /api/canary-deployments/metrics
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'model_router_canary_.*'
      action: keep
    - sourceLabels: [deployment_id]
      targetLabel: canary_deployment
      replacement: '${1}'

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smm-model-evaluation
  namespace: monitoring
  labels:
    app: model-router
    component: evaluation-monitoring
    smm.architect/service: model-evaluation
spec:
  jobLabel: model-evaluation
  selector:
    matchLabels:
      app: model-router
      component: evaluation
  endpoints:
  - port: http-metrics
    path: /api/evaluations/metrics
    interval: 60s
    scrapeTimeout: 15s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'model_router_evaluation_.*|model_router_drift_.*|model_router_ab_test_.*'
      action: keep
    - sourceLabels: [evaluation_id]
      targetLabel: evaluation
      replacement: '${1}'

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smm-workspace-budgets
  namespace: monitoring
  labels:
    app: smm-architect
    component: budget-monitoring
    smm.architect/service: workspace-budgets
spec:
  jobLabel: workspace-budgets
  selector:
    matchLabels:
      app: workspace-api
      component: budget
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'smm_workspace_budget_.*|smm_workspace_cost_.*'
      action: keep
    - sourceLabels: [workspace_id]
      targetLabel: workspace
      replacement: '${1}'
    - sourceLabels: [tenant_id]
      targetLabel: tenant
      replacement: '${1}'

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smm-mcp-workflows
  namespace: monitoring
  labels:
    app: n8n
    component: mcp-monitoring
    smm.architect/service: mcp-workflows
spec:
  jobLabel: mcp-workflows
  selector:
    matchLabels:
      app: n8n
      component: mcp
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'n8n_workflow_.*|mcp_.*'
      action: keep
    - sourceLabels: [workflow_id]
      targetLabel: workflow
      replacement: '${1}'
    - sourceLabels: [protocol]
      regex: 'mcp-2.0'
      action: keep