{{- if .Values.networkPolicy.enabled }}
{{- range $service, $dummy := dict "core-service" true "toolhub" true "frontend" true "model-router" true "publisher" true "agents" true }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "smm-architect.fullname" $ }}-{{ $service }}
  labels:
    {{- include "smm-architect.labels" $ | nindent 4 }}
    {{- include "smm-architect.componentLabels" $service | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "smm-architect.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $service }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: http
          protocol: TCP
---
{{- end }}
{{- end }}