{{- range $service, $config := dict "core-service" (dict "port" .Values.service.ports.coreService) "toolhub" (dict "port" .Values.service.ports.toolhub) "model-router" (dict "port" .Values.service.ports.modelRouter) "publisher" (dict "port" .Values.service.ports.publisher) "agents" (dict "port" .Values.service.ports.agents) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smm-architect.fullname" $ }}-{{ $service }}
  labels:
    {{- include "smm-architect.labels" $ | nindent 4 }}
    {{- include "smm-architect.componentLabels" $service | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smm-architect.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
{{- end }}