apiVersion: v1
kind: ConfigMap
metadata:
  name: smm-architect-config
  namespace: smm-architect
  labels:
    app.kubernetes.io/name: smm-architect
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  POSTGRES_DB: "smm_architect"
  POSTGRES_USER: "smm_user"
  REDIS_URL: "redis://smm-redis:6379"
  VAULT_URL: "http://smm-vault:8200"
  SENTRY_ENVIRONMENT: "production"
  API_URL: "https://api.smm-architect.com"
  TOOLHUB_URL: "https://toolhub.smm-architect.com"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smm-architect-nginx-config
  namespace: smm-architect
data:
  nginx.conf: |
    upstream smm_architect_backend {
        server smm-architect-service:4000;
    }
    
    upstream toolhub_backend {
        server smm-toolhub-service:3001;
    }
    
    upstream frontend_backend {
        server smm-frontend-service:3000;
    }
    
    server {
        listen 80;
        server_name api.smm-architect.com;
        
        location / {
            proxy_pass http://smm_architect_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            proxy_pass http://smm_architect_backend/health;
        }
    }
    
    server {
        listen 80;
        server_name toolhub.smm-architect.com;
        
        location / {
            proxy_pass http://toolhub_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    server {
        listen 80;
        server_name app.smm-architect.com;
        
        location / {
            proxy_pass http://frontend_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }