apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smm-redis
  namespace: smm-architect
  labels:
    app.kubernetes.io/name: smm-architect
    app.kubernetes.io/component: redis
spec:
  serviceName: smm-redis
  replicas: 1
  selector:
    matchLabels:
      app: smm-redis
  template:
    metadata:
      labels:
        app: smm-redis
        app.kubernetes.io/name: smm-architect
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "768mb"
        - --maxmemory-policy
        - "allkeys-lru"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast-ssd

---
apiVersion: v1
kind: Service
metadata:
  name: smm-redis
  namespace: smm-architect
  labels:
    app.kubernetes.io/name: smm-architect
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: smm-redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smm-postgres
  namespace: smm-architect
  labels:
    app.kubernetes.io/name: smm-architect
    app.kubernetes.io/component: postgres
spec:
  serviceName: smm-postgres
  replicas: 1
  selector:
    matchLabels:
      app: smm-postgres
  template:
    metadata:
      labels:
        app: smm-postgres
        app.kubernetes.io/name: smm-architect
        app.kubernetes.io/component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: smm_architect
        - name: POSTGRES_USER
          value: smm_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smm-architect-secrets
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
      storageClassName: fast-ssd

---
apiVersion: v1
kind: Service
metadata:
  name: smm-postgres
  namespace: smm-architect
  labels:
    app.kubernetes.io/name: smm-architect
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: smm-postgres