# Prometheus configuration for SMM Architect
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smm-architect'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # SMM Architect Monitoring Service
  - job_name: 'smm-metrics'
    static_configs:
      - targets: ['smm-metrics:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # SMM Architect Core Service
  - job_name: 'smm-architect'
    static_configs:
      - targets: ['smm-architect:3005']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # ToolHub Service
  - job_name: 'toolhub'
    static_configs:
      - targets: ['toolhub:3001']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Simulator Service
  - job_name: 'simulator'
    static_configs:
      - targets: ['simulator:3002']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Agents Service
  - job_name: 'agents'
    static_configs:
      - targets: ['agents:3003']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Audit Service
  - job_name: 'audit'
    static_configs:
      - targets: ['audit:3004']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Workspace Provisioning Service
  - job_name: 'workspace-provisioning'
    static_configs:
      - targets: ['workspace-provisioning:3006']
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 15s

  # PostgreSQL Database (with postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache (with redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Vault (HashiCorp Vault metrics)
  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scrape_interval: 30s
    scrape_timeout: 10s
    bearer_token_file: /etc/prometheus/vault-token

  # Kubernetes cluster metrics (if running on K8s)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # AWS CloudWatch metrics (if running on AWS)
  - job_name: 'cloudwatch'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      max_shards: 200
      min_shards: 1
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms